---
version: 2
jobs:
  build:
    working_directory: /root/kaffeine

    docker:
      - image: avvo/elixir-circleci:1.4.1-3
      - image: jplock/zookeeper:3.4.6
      - image: ches/kafka:0.8.2.2
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_NUM_PARTITIONS: 12
          KAFKA_DELETE_TOPIC_ENABLE: "true"
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    environment:
      MIX_ENV: test
      KAFKA_HOSTS: kafka:9092

    steps:
      - checkout

      - run:
          name: Wait for kafka to start
          command: ./bin/wait_for_it.sh kafka:9092

      - restore_cache:
          key: kaffeine-{{ .Branch }}
          key: kaffeine-master

      - run: mix do deps.get, deps.compile, compile

      - run:
          name: Run Tests
          command: mix test

      - run: mix dialyzer

      - save_cache:
          key: kaffeine-{{ .Branch }}
          paths:
            - _build
            - deps
            - .local.plt
            - .local.plt.hash
